# Generated by Django 2.2.28 on 2025-04-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='event_date',
            field=models.DateField(),
        ),
    ]
