# Generated by Django 2.2.28 on 2025-04-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brawl', '0002_auto_20250414_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
