# Generated by Django 2.2.28 on 2025-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawl', '0004_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
