# Generated by Django 2.2.28 on 2025-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawl', '0006_auto_20250416_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='draws',
            field=models.IntegerField(default=0),
        ),
    ]
